## NumPy 
(NumPy stands for Numerical Python)


NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra and matrices.


**Why Use NumPy?**


In Python we have lists that serve the purpose of arrays, but they are slow to process.
**NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.**
The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.


Numpy code is in c which makes it much faster than Python (closer to the hardware level)

## Installation of NumPy

In [4]:
!pip install --upgrade pip
!pip install numpy

  Using cached pip-25.0-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-25.0-py3-none-any.whl (1.8 MB)


ERROR: To modify pip, please run the following command:
C:\Users\AYA\Documents\New folder\envs\depi_env\python.exe -m pip install --upgrade pip


In [5]:
#Create a NumPy ndarray Object

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
#Checking NumPy Version
print(np.__version__)

2.2.1


To create an ndarray, we can pass a list, tuple into the array() method, and it will be converted into an ndarray

In [7]:
# Try it yourself
# Creating an ndarray from a list
list_array = np.array([1, 2, 3, 4, 5])
print(list_array)

# Creating an ndarray from a tuple
tuple_array = np.array((1, 2, 3, 4, 5))
print(tuple_array)

[1 2 3 4 5]
[1 2 3 4 5]


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

**nested array:** are arrays that have arrays as their elements.


In [8]:
# 0-D Arrays
arr = np.array(42)
print(arr)

42


In [10]:
# 1-D Arrays
# Try it yourself -- from a Tuple
arr = np.array((1,2))
print(arr)

[1 2]


In [11]:
# 2-D Arrays
#An array that has 1-D arrays as its elements is called a 2-D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
# 3-D arrays
# Try it yourself
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.


a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.




In [14]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Indexing


Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.



In [15]:
# Create a numpy array and access the first element in it
arr = np.array([1, 2, 3, 4])
arr[0]

np.int64(1)

In [16]:
# Try accessing 2 elements in a numpy array and adding them together
arr = np.array([1, 2, 3, 4])
addition=arr[0]+arr[1]
print(addition)

3


In [17]:
# Access 2-D Arrays

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])
arr[0][1]

2nd element on 1st dim:  2


np.int64(2)

In [19]:
# Access 3-D Arrays
# Try it yourself

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print('1st element on 1st dim: ', arr[0, 0, 0])
arr[0][0][0]

1st element on 1st dim:  1


np.int64(1)

## NumPy Array Slicing
We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].



In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [22]:
# question for you?
# create a numpy array and slice the last 2 items in it.
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-2:])

[6 7]


In [23]:
#Step
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:3])

[2 5]


In [24]:
print(arr[::2])

[1 3 5 7]


In [27]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
# Try it yourself

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# Slicing index 1 to index 4 (not included)
sliced_arr = arr[:, 1:4]

print(sliced_arr)


[[2 3 4]
 [7 8 9]]


In [26]:
# Checking the Data Type of an Array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


## Array Shape


The shape of an array is the number of elements in each dimension.


In [28]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
print(arr.shape)

(2, 4)


In [30]:
# Joining Array
# Joining means putting contents of two or more arrays in a single array.
arr1 = np.array([1, 2, 3, 6])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 6 4 5 6]


In [31]:
# Join two 2-D arrays along columns (axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [32]:
# Join two 2-D arrays along rows (axis=0):
# Try it yourself
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [33]:
#Splitting Array
#Splitting is reverse operation of Joining.
arr = np.array([1, 2, 3, 4, 5, 6, 7])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3, 4]), array([5, 6, 7])]
